version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            APP_ENV: local
            APP_DEBUG: 1
        depends_on:
            - db

    db:
        image: nouchka/sqlite3
        volumes:
            - ./database:/database
        command: tail -f /dev/null
